Don't copy the result to the clipboard if importing the clipboard library raises an exception
In travis ci here is the exception:

 File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyperclip/__init__.py", line 200, in <module>
    raise Exception('Pyperclip requires the xclip or xsel application, or the gtk or PyQt4 module.')
Exception: Pyperclip requires the xclip or xsel application, or the gtk or PyQt4 module.